x = 3


def scopeError():
    print(x)
    x = 5


scopeError()
